/**
 * @fileoverview gRPC-Web generated client stub for api
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: api.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.api = require('./api_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.DeviceProfileServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.api.DeviceProfileServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.GetVendorRequest,
 *   !proto.api.GetVendorResponse>}
 */
const methodDescriptor_DeviceProfileService_GetVendor = new grpc.web.MethodDescriptor(
  '/api.DeviceProfileService/GetVendor',
  grpc.web.MethodType.UNARY,
  proto.api.GetVendorRequest,
  proto.api.GetVendorResponse,
  /**
   * @param {!proto.api.GetVendorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.GetVendorResponse.deserializeBinary
);


/**
 * @param {!proto.api.GetVendorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.GetVendorResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.GetVendorResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.DeviceProfileServiceClient.prototype.getVendor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.DeviceProfileService/GetVendor',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_GetVendor,
      callback);
};


/**
 * @param {!proto.api.GetVendorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.GetVendorResponse>}
 *     Promise that resolves to the response
 */
proto.api.DeviceProfileServicePromiseClient.prototype.getVendor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.DeviceProfileService/GetVendor',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_GetVendor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.CreateVendorRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_DeviceProfileService_CreateVendor = new grpc.web.MethodDescriptor(
  '/api.DeviceProfileService/CreateVendor',
  grpc.web.MethodType.UNARY,
  proto.api.CreateVendorRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.api.CreateVendorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.api.CreateVendorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.DeviceProfileServiceClient.prototype.createVendor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.DeviceProfileService/CreateVendor',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_CreateVendor,
      callback);
};


/**
 * @param {!proto.api.CreateVendorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.api.DeviceProfileServicePromiseClient.prototype.createVendor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.DeviceProfileService/CreateVendor',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_CreateVendor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.UpdateVendorRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_DeviceProfileService_UpdateVendor = new grpc.web.MethodDescriptor(
  '/api.DeviceProfileService/UpdateVendor',
  grpc.web.MethodType.UNARY,
  proto.api.UpdateVendorRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.api.UpdateVendorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.api.UpdateVendorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.DeviceProfileServiceClient.prototype.updateVendor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.DeviceProfileService/UpdateVendor',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_UpdateVendor,
      callback);
};


/**
 * @param {!proto.api.UpdateVendorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.api.DeviceProfileServicePromiseClient.prototype.updateVendor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.DeviceProfileService/UpdateVendor',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_UpdateVendor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.api.ListVendorsResponse>}
 */
const methodDescriptor_DeviceProfileService_ListVendors = new grpc.web.MethodDescriptor(
  '/api.DeviceProfileService/ListVendors',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.api.ListVendorsResponse,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.ListVendorsResponse.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.ListVendorsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.ListVendorsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.DeviceProfileServiceClient.prototype.listVendors =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.DeviceProfileService/ListVendors',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_ListVendors,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.ListVendorsResponse>}
 *     Promise that resolves to the response
 */
proto.api.DeviceProfileServicePromiseClient.prototype.listVendors =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.DeviceProfileService/ListVendors',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_ListVendors);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.DeleteVendorRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_DeviceProfileService_DeleteVendor = new grpc.web.MethodDescriptor(
  '/api.DeviceProfileService/DeleteVendor',
  grpc.web.MethodType.UNARY,
  proto.api.DeleteVendorRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.api.DeleteVendorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.api.DeleteVendorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.DeviceProfileServiceClient.prototype.deleteVendor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.DeviceProfileService/DeleteVendor',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_DeleteVendor,
      callback);
};


/**
 * @param {!proto.api.DeleteVendorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.api.DeviceProfileServicePromiseClient.prototype.deleteVendor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.DeviceProfileService/DeleteVendor',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_DeleteVendor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.CreateCodecRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_DeviceProfileService_CreateCodec = new grpc.web.MethodDescriptor(
  '/api.DeviceProfileService/CreateCodec',
  grpc.web.MethodType.UNARY,
  proto.api.CreateCodecRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.api.CreateCodecRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.api.CreateCodecRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.DeviceProfileServiceClient.prototype.createCodec =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.DeviceProfileService/CreateCodec',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_CreateCodec,
      callback);
};


/**
 * @param {!proto.api.CreateCodecRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.api.DeviceProfileServicePromiseClient.prototype.createCodec =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.DeviceProfileService/CreateCodec',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_CreateCodec);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.GetCodecRequest,
 *   !proto.api.GetCodecResponse>}
 */
const methodDescriptor_DeviceProfileService_GetCodec = new grpc.web.MethodDescriptor(
  '/api.DeviceProfileService/GetCodec',
  grpc.web.MethodType.UNARY,
  proto.api.GetCodecRequest,
  proto.api.GetCodecResponse,
  /**
   * @param {!proto.api.GetCodecRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.GetCodecResponse.deserializeBinary
);


/**
 * @param {!proto.api.GetCodecRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.GetCodecResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.GetCodecResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.DeviceProfileServiceClient.prototype.getCodec =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.DeviceProfileService/GetCodec',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_GetCodec,
      callback);
};


/**
 * @param {!proto.api.GetCodecRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.GetCodecResponse>}
 *     Promise that resolves to the response
 */
proto.api.DeviceProfileServicePromiseClient.prototype.getCodec =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.DeviceProfileService/GetCodec',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_GetCodec);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.UpdateCodecRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_DeviceProfileService_UpdateCodec = new grpc.web.MethodDescriptor(
  '/api.DeviceProfileService/UpdateCodec',
  grpc.web.MethodType.UNARY,
  proto.api.UpdateCodecRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.api.UpdateCodecRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.api.UpdateCodecRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.DeviceProfileServiceClient.prototype.updateCodec =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.DeviceProfileService/UpdateCodec',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_UpdateCodec,
      callback);
};


/**
 * @param {!proto.api.UpdateCodecRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.api.DeviceProfileServicePromiseClient.prototype.updateCodec =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.DeviceProfileService/UpdateCodec',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_UpdateCodec);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.ListCodecsRequest,
 *   !proto.api.ListCodecsResponse>}
 */
const methodDescriptor_DeviceProfileService_ListCodecs = new grpc.web.MethodDescriptor(
  '/api.DeviceProfileService/ListCodecs',
  grpc.web.MethodType.UNARY,
  proto.api.ListCodecsRequest,
  proto.api.ListCodecsResponse,
  /**
   * @param {!proto.api.ListCodecsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.api.ListCodecsResponse.deserializeBinary
);


/**
 * @param {!proto.api.ListCodecsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.api.ListCodecsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.api.ListCodecsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.DeviceProfileServiceClient.prototype.listCodecs =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.DeviceProfileService/ListCodecs',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_ListCodecs,
      callback);
};


/**
 * @param {!proto.api.ListCodecsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.api.ListCodecsResponse>}
 *     Promise that resolves to the response
 */
proto.api.DeviceProfileServicePromiseClient.prototype.listCodecs =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.DeviceProfileService/ListCodecs',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_ListCodecs);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.api.DeleteCodecRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_DeviceProfileService_DeleteCodec = new grpc.web.MethodDescriptor(
  '/api.DeviceProfileService/DeleteCodec',
  grpc.web.MethodType.UNARY,
  proto.api.DeleteCodecRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.api.DeleteCodecRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.api.DeleteCodecRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.api.DeviceProfileServiceClient.prototype.deleteCodec =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/api.DeviceProfileService/DeleteCodec',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_DeleteCodec,
      callback);
};


/**
 * @param {!proto.api.DeleteCodecRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.api.DeviceProfileServicePromiseClient.prototype.deleteCodec =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/api.DeviceProfileService/DeleteCodec',
      request,
      metadata || {},
      methodDescriptor_DeviceProfileService_DeleteCodec);
};


module.exports = proto.api;

