[package]
  name = "test-runner"
  version = "0.1.0"
  edition = "2021"

[dependencies]
  serde = { version = "1.0", features = ["derive"] }
  serde_valid = "0.24"
  toml = "0.8"
  rquickjs = { version = "0.6", features = ["loader", "array-buffer"] }
